GET http://localhost:4444/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWF0dCIsImlhdCI6MTY5MjAyOTkxNSwiZXhwIjoxNjkyMDI5OTYwfQ.CENwSY0eyhdp9zEJdtCNxZzTcwvXIjfyjbigZfUdl64

###

DELETE http://localhost:1000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWF0dCIsImlhdCI6MTY5MjAyOTkxNX0.kJqbZxidP9oVIqnu32ogXB8PlH7yeRrl2dtqZusgRZc"
}


###

POST http://localhost:1000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWF0dCIsImlhdCI6MTY5MjAyOTkxNX0.kJqbZxidP9oVIqnu32ogXB8PlH7yeRrl2dtqZusgRZc"
}

###

POST http://localhost:1000/login
Content-Type: application/json

  {
    "username": "Matt"
  }
